export {
  PIPELINE_KINDS,
  STAGE_STALE_DAYS,
  closeDateOf,
  dealHealthScore,
  daysInStage,
  dealsByOpenStage,
  filterDeals,
  isClosedStage,
  isStageStale,
  nextStageId,
  openDeals,
  openPipeline,
  pipelineVelocity,
  siteCount,
  stageById,
  stageEnteredAt,
  weightedPipeline,
  weightedValue,
  wonRevenue,
  type DealFilters,
  type PipelineKind,
} from "./pipeline";
