export const NAV = [
  { href: "/", label: "Home", hint: "00" },
  { href: "/offers", label: "Offers", hint: "01" },
  { href: "/proof", label: "Proof", hint: "02" },
  { href: "/people", label: "Contacts", hint: "03" },
  { href: "/callbacks", label: "Follow-up", hint: "04" },
  { href: "/appointments", label: "Appointments", hint: "05" },
  { href: "/floor", label: "Dialer", hint: "06" },
  { href: "/design", label: "Design", hint: "07" },
  { href: "/map", label: "Map", hint: "08" },
  { href: "/board", label: "Pipeline", hint: "09" },
  { href: "/numbers", label: "Reports", hint: "10" },
  { href: "/money", label: "Revenue", hint: "11" },
  { href: "/analytics", label: "Analytics", hint: "12" },
  { href: "/studio", label: "Studio", hint: "13" },
  { href: "/investment", label: "Investment", hint: "14" },
  { href: "/ads", label: "Ads", hint: "15" },
  { href: "/settings", label: "Settings", hint: "16" },
];
