import type { Appointment, Callback, Lead, Opportunity, RoofDesign, Workspace } from "./types";
import { defaultDesign } from "./solar";
import { ensureSite } from "./site";

function offset(days: number, hour = 10) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

function atHour(hour: number, minute = 0) {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export function emptyWorkspace(): Workspace {
  return {
    version: 2,
    brand: "azimuth",
    leads: [],
    opportunities: [],
    callbacks: [],
    appointments: [],
    activities: [],
    kpiEvents: [],
    designs: {},
    proposals: {},
    callLogs: [],
    settings: {
      operator: "Michael",
      dialTarget: 80,
      defaultOwner: "Michael",
      density: "comfortable",
    },
    updatedAt: new Date().toISOString(),
  };
}

export function createSeed(): Workspace {
  const created = new Date().toISOString();

  const leads: Lead[] = [
    {
      id: "lead-casey",
      name: "Casey Morgan",
      property: "Morgan Residence",
      phone: "+16615550102",
      email: "casey.morgan@example.test",
      city: "Bakersfield",
      utility: "PG&E",
      monthlyBill: 315,
      status: "Promising Callback",
      priority: "Critical",
      owner: "Michael",
      source: "Referral",
      consent: "verified",
      dnc: false,
      attempts: 3,
      nextAction: "Review utility bill and lock a consult",
      nextFollowUp: atHour(14),
      estimatedValue: 24000,
      notes: "Homeowner. South-facing composition roof. Asked to call after lunch.",
      homeowner: "Yes",
      createdAt: offset(-6, 9),
      updatedAt: created,
    },
    {
      id: "lead-riley",
      name: "Riley Chen",
      property: "Chen Property Group",
      phone: "+15593210104",
      email: "riley.chen@example.test",
      city: "Fresno",
      utility: "PG&E",
      monthlyBill: 480,
      status: "Proposal",
      priority: "High",
      owner: "Avery",
      source: "Partner",
      consent: "verified",
      dnc: false,
      attempts: 4,
      nextAction: "Answer remaining proposal questions",
      nextFollowUp: offset(-1, 15),
      estimatedValue: 46500,
      notes: "Two structures. Wants production guarantee in writing before signing.",
      homeowner: "Yes",
      createdAt: offset(-18, 11),
      updatedAt: created,
    },
    {
      id: "lead-taylor",
      name: "Taylor Brooks",
      property: "Brooks Family",
      phone: "+16195550103",
      email: "taylor.brooks@example.test",
      city: "San Diego",
      utility: "SDG&E",
      monthlyBill: 268,
      status: "Appointment Set",
      priority: "High",
      owner: "Avery",
      source: "Google Ads",
      consent: "verified",
      dnc: false,
      attempts: 1,
      nextAction: "Confirm tomorrow’s consult and send agenda",
      nextFollowUp: offset(1, 8),
      estimatedValue: 32000,
      notes: "Both decision-makers on the call. Interested in battery backup.",
      homeowner: "Yes",
      createdAt: offset(-4, 16),
      updatedAt: created,
    },
    {
      id: "lead-jordan",
      name: "Jordan Lee",
      property: "BrightPeak Solar",
      phone: "+16615550101",
      email: "jordan.lee@example.test",
      city: "Bakersfield",
      utility: "PG&E",
      monthlyBill: 210,
      status: "Qualified",
      priority: "High",
      owner: "Michael",
      source: "Website form",
      consent: "verified",
      dnc: false,
      attempts: 2,
      nextAction: "Confirm site survey window",
      nextFollowUp: atHour(11),
      estimatedValue: 18500,
      notes: "Qualified on bill and roof age. Survey is the bottleneck.",
      homeowner: "Yes",
      createdAt: offset(-8, 10),
      updatedAt: created,
    },
    {
      id: "lead-omar",
      name: "Omar Haddad",
      property: "Haddad Home",
      phone: "+17025550121",
      email: "omar.haddad@example.test",
      city: "Las Vegas",
      utility: "NV Energy",
      monthlyBill: 342,
      status: "Appointment Confirmed",
      priority: "High",
      owner: "Michael",
      source: "Event",
      consent: "verified",
      dnc: false,
      attempts: 2,
      nextAction: "Run the sit — closer packet is ready",
      nextFollowUp: atHour(18, 30),
      estimatedValue: 28900,
      notes: "Confirmed for this evening. HOA packet already collected.",
      homeowner: "Yes",
      createdAt: offset(-3, 13),
      updatedAt: created,
    },
    {
      id: "lead-nina",
      name: "Nina Solis",
      property: "Solis Residence",
      phone: "+16025550133",
      email: "nina.solis@example.test",
      city: "Phoenix",
      utility: "APS",
      monthlyBill: 390,
      status: "Qualified",
      priority: "Medium",
      owner: "Avery",
      source: "Organic",
      consent: "verified",
      dnc: false,
      attempts: 2,
      nextAction: "Set consult after rate-plan walkthrough",
      nextFollowUp: offset(0, 16),
      estimatedValue: 27600,
      notes: "High summer bill. Wants to understand TOU before a sit.",
      homeowner: "Yes",
      createdAt: offset(-5, 12),
      updatedAt: created,
    },
    {
      id: "lead-maya",
      name: "Maya Okonkwo",
      property: "Okonkwo Residence",
      phone: "+19165550144",
      email: "maya.okonkwo@example.test",
      city: "Sacramento",
      utility: "SMUD",
      monthlyBill: 198,
      status: "Contract Sent",
      priority: "High",
      owner: "Avery",
      source: "Referral",
      consent: "verified",
      dnc: false,
      attempts: 5,
      nextAction: "Nudge on DocuSign — 6 days in paper",
      nextFollowUp: offset(0, 17),
      estimatedValue: 22100,
      notes: "Contract sent. Waiting on co-signer traveling until Friday.",
      homeowner: "Yes",
      createdAt: offset(-21, 9),
      updatedAt: created,
    },
    {
      id: "lead-luis",
      name: "Luis Navarro",
      property: "Navarro Property",
      phone: "+15592550155",
      email: "luis.navarro@example.test",
      city: "Fresno",
      utility: "PG&E",
      monthlyBill: 255,
      status: "Design",
      priority: "Medium",
      owner: "Michael",
      source: "Partner",
      consent: "verified",
      dnc: false,
      attempts: 3,
      nextAction: "Send array layout for shade review",
      nextFollowUp: offset(1, 11),
      estimatedValue: 31200,
      notes: "Survey complete. Western oak line needs shade study.",
      homeowner: "Yes",
      createdAt: offset(-24, 14),
      updatedAt: created,
    },
    {
      id: "lead-helen",
      name: "Helen Park",
      property: "Park Residence",
      phone: "+16265550166",
      email: "helen.park@example.test",
      city: "Riverside",
      utility: "SCE",
      monthlyBill: 176,
      status: "Attempting Contact",
      priority: "Medium",
      owner: "Unassigned",
      source: "Google Ads",
      consent: "verified",
      dnc: false,
      attempts: 1,
      nextAction: "Second attempt before 11am PT",
      nextFollowUp: offset(0, 10),
      estimatedValue: 15400,
      notes: "Form fill last night. No voicemail yet.",
      homeowner: "Yes",
      createdAt: offset(-1, 21),
      updatedAt: created,
    },
    {
      id: "lead-sam",
      name: "Sam Rivera",
      property: "Rivera Home",
      phone: "+18055550105",
      email: "sam.rivera@example.test",
      city: "Stockton",
      utility: "PG&E",
      monthlyBill: 142,
      status: "New Lead",
      priority: "Medium",
      owner: "Unassigned",
      source: "Organic",
      consent: "unknown",
      dnc: false,
      attempts: 0,
      nextAction: "Verify consent before first dial",
      nextFollowUp: offset(0, 9),
      estimatedValue: 12800,
      notes: "Inbound form. Consent checkbox was blank.",
      homeowner: "Unknown",
      createdAt: offset(0, 8),
      updatedAt: created,
    },
    {
      id: "lead-drew",
      name: "Drew Patel",
      property: "Patel Residence",
      phone: "+18585550177",
      email: "drew.patel@example.test",
      city: "San Diego",
      utility: "SDG&E",
      monthlyBill: 224,
      status: "PTO",
      priority: "Low",
      owner: "Michael",
      source: "Referral",
      consent: "verified",
      dnc: false,
      attempts: 6,
      nextAction: "PTO packet in with SDG&E",
      nextFollowUp: offset(3, 10),
      estimatedValue: 19800,
      notes: "Installed last week. Monitoring live. PTO pending.",
      homeowner: "Yes",
      createdAt: offset(-62, 10),
      updatedAt: created,
    },
    {
      id: "lead-grace",
      name: "Grace Nguyen",
      property: "Nguyen Residence",
      phone: "+14085550188",
      email: "grace.nguyen@example.test",
      city: "San Jose",
      utility: "PG&E",
      monthlyBill: 188,
      status: "New Lead",
      priority: "Low",
      owner: "Unassigned",
      source: "Purchased list",
      consent: "missing",
      dnc: true,
      attempts: 0,
      nextAction: "Do not contact — internal DNC",
      nextFollowUp: "",
      estimatedValue: 0,
      notes: "Requested no contact. Suppressed.",
      homeowner: "Yes",
      createdAt: offset(-12, 15),
      updatedAt: created,
    },
  ];

  const stageEntered: Record<string, string> = {
    "lead-casey": offset(-2, 14),
    "lead-riley": offset(-12, 9),
    "lead-taylor": offset(-1, 16),
    "lead-jordan": offset(-3, 11),
    "lead-omar": offset(0, 9),
    "lead-nina": offset(-2, 16),
    "lead-maya": offset(-6, 10),
    "lead-luis": offset(-5, 13),
    "lead-helen": offset(-1, 21),
    "lead-sam": offset(0, 8),
    "lead-drew": offset(-4, 12),
  };

  const probabilities: Record<string, number> = {
    "New Lead": 8,
    "Attempting Contact": 12,
    "Contacted": 18,
    "Qualified": 35,
    "Promising Callback": 42,
    "Appointment Set": 55,
    "Appointment Confirmed": 62,
    "Appointment Sat": 70,
    "Proposal": 58,
    "Contract Sent": 74,
    "Contract Signed": 86,
    "Site Survey": 88,
    "Design": 90,
    "Permitting": 92,
    "Installation Scheduled": 94,
    "Installed": 96,
    "PTO": 98,
    "Closed Won": 100,
    "Closed Lost": 0,
    "Cancelled": 0,
  };

  const opportunities: Opportunity[] = leads
    .filter((lead) => lead.id !== "lead-grace")
    .map((lead) => ({
      id: `opp-${lead.id.replace("lead-", "")}`,
      leadId: lead.id,
      name: lead.name,
      property: lead.property,
      stage: lead.status,
      value: lead.estimatedValue,
      probability: probabilities[lead.status] ?? 20,
      owner: lead.owner,
      source: lead.source,
      nextAction: lead.nextAction,
      expectedClose: lead.status === "PTO" ? offset(10, 12).slice(0, 10) : offset(18, 12).slice(0, 10),
      notes: lead.notes,
      createdAt: lead.createdAt,
      updatedAt: created,
      stageEnteredAt: stageEntered[lead.id] || lead.createdAt,
      history: [],
    }));

  const callbacks: Callback[] = [
    {
      id: "cb-casey",
      leadId: "lead-casey",
      type: "promising",
      dueAt: atHour(14),
      reason: "Review utility bill and qualification questions",
      assignedUser: "Michael",
      notes: "Promised a callback after lunch.",
      status: "open",
      createdAt: offset(-1, 14),
    },
    {
      id: "cb-riley",
      leadId: "lead-riley",
      type: "hot",
      dueAt: offset(-1, 15),
      reason: "Proposal questions still open",
      assignedUser: "Avery",
      notes: "Overdue. Production guarantee language.",
      status: "open",
      createdAt: offset(-3, 15),
    },
    {
      id: "cb-taylor",
      leadId: "lead-taylor",
      type: "confirmation",
      dueAt: offset(1, 8),
      reason: "Confirm tomorrow’s consultation",
      assignedUser: "Avery",
      notes: "Both spouses on the sit.",
      status: "open",
      createdAt: offset(-1, 16),
    },
    {
      id: "cb-helen",
      leadId: "lead-helen",
      type: "standard",
      dueAt: offset(0, 10),
      reason: "Second dial attempt",
      assignedUser: "Michael",
      notes: "No VM on first pass.",
      status: "open",
      createdAt: offset(-1, 21),
    },
    {
      id: "cb-sam",
      leadId: "lead-sam",
      type: "standard",
      dueAt: offset(0, 9),
      reason: "Verify TCPA consent before first dial",
      assignedUser: "Michael",
      notes: "Form consent was blank.",
      status: "open",
      createdAt: created,
    },
  ];

  const appointments: Appointment[] = [
    {
      id: "appt-omar",
      leadId: "lead-omar",
      type: "Solar consultation",
      startsAt: atHour(18, 30),
      duration: 75,
      setter: "Avery",
      closer: "Michael",
      location: "Video",
      status: "confirmed",
      notes: "Closer packet ready. HOA docs attached.",
      createdAt: offset(-2, 11),
    },
    {
      id: "appt-taylor",
      leadId: "lead-taylor",
      type: "Solar consultation",
      startsAt: offset(1, 10),
      duration: 45,
      setter: "Avery",
      closer: "Michael",
      location: "Video",
      status: "needs confirmation",
      notes: "Battery interest. Confirm AM.",
      createdAt: offset(-1, 16),
    },
    {
      id: "appt-jordan",
      leadId: "lead-jordan",
      type: "Site survey",
      startsAt: offset(2, 13),
      duration: 60,
      setter: "Michael",
      closer: "Michael",
      location: "Customer site",
      status: "scheduled",
      notes: "Need attic access.",
      createdAt: offset(-3, 11),
    },
  ];

  return {
    version: 1,
    brand: "azimuth",
    leads,
    opportunities,
    callbacks,
    appointments,
    activities: [
      {
        id: "act-seed",
        entityType: "workspace",
        entityId: "azimuth",
        type: "seeded",
        detail: "Starter workspace loaded. Labeled example records only.",
        at: created,
      },
    ],
    kpiEvents: [
      { id: "kpi-1", type: "dial_attempt", leadId: "lead-jordan", at: offset(-3, 10) },
      { id: "kpi-2", type: "connected_call", leadId: "lead-jordan", at: offset(-3, 10) },
      { id: "kpi-3", type: "qualified_lead", leadId: "lead-jordan", at: offset(-2, 11) },
      { id: "kpi-4", type: "appointment_set", leadId: "lead-taylor", at: offset(-1, 16) },
      { id: "kpi-5", type: "appointment_confirmed", leadId: "lead-omar", at: offset(0, 9) },
      { id: "kpi-6", type: "dial_attempt", leadId: "lead-helen", at: offset(-1, 21) },
      { id: "kpi-7", type: "dial_attempt", leadId: "lead-casey", at: offset(-2, 14) },
      { id: "kpi-8", type: "connected_call", leadId: "lead-casey", at: offset(-2, 14) },
    ],
    designs: Object.fromEntries(leads.map((lead) => [lead.id, defaultDesign(lead)])) as Record<string, RoofDesign>,
    proposals: Object.fromEntries(
      leads
        .filter((lead) => /Proposal|Contract|Design|PTO/.test(lead.status))
        .map((lead) => [
          lead.id,
          {
            leadId: lead.id,
            status: lead.status === "PTO" ? "Presented" : lead.status.includes("Contract") ? "Presented" : "Internal review",
            version: 1,
            notes: lead.notes,
            updatedAt: created,
          },
        ]),
    ),
    callLogs: [],
    settings: {
      operator: "Michael",
      dialTarget: 80,
      defaultOwner: "Michael",
      density: "comfortable",
    },
    updatedAt: created,
  };
}

export function normalizeWorkspace(workspace: Workspace): Workspace {
  const designs = { ...(workspace.designs || {}) };
  for (const lead of workspace.leads) {
    designs[lead.id] = ensureSite(designs[lead.id] || defaultDesign(lead));
    if (designs[lead.id].lat == null || designs[lead.id].lng == null) {
      const fresh = defaultDesign(lead);
      designs[lead.id] = { ...designs[lead.id], lat: fresh.lat, lng: fresh.lng };
    }
  }
  return {
    ...workspace,
    version: 2,
    designs,
    proposals: workspace.proposals || {},
    callLogs: workspace.callLogs || [],
  };
}

export function isWorkspace(value: unknown): value is Workspace {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return record.brand === "azimuth" && Array.isArray(record.leads) && Array.isArray(record.opportunities);
}
