import type { Appointment, Callback, Company, FreightAnalysis, Lead, Listing, Opportunity, Quote, SavedSearch, Shipment, Workspace } from "./types";
import { blankProspect } from "./freight";
import { mapLegacyStage } from "./stages";

function offset(days: number, hour = 10) {
  const date = new Date();
  date.setDate(date.getDate() + days);
  date.setHours(hour, 0, 0, 0);
  return date.toISOString();
}

function atHour(hour: number, minute = 0) {
  const date = new Date();
  date.setHours(hour, minute, 0, 0);
  return date.toISOString();
}

export function emptyWorkspace(): Workspace {
  return {
    version: 3,
    brand: "azimuth",
    leads: [],
    opportunities: [],
    callbacks: [],
    appointments: [],
    activities: [],
    kpiEvents: [],
    designs: {},
    proposals: {},
    callLogs: [],
    listings: [],
    companies: [],
    quotes: [],
    shipments: [],
    carriers: [],
    savedSearches: [],
    analyses: [],
    settings: {
      operator: "Michael",
      dialTarget: 80,
      defaultOwner: "Michael",
      density: "comfortable",
    },
    updatedAt: new Date().toISOString(),
    revision: 0,
  };
}

function lead(partial: Partial<Lead> & Pick<Lead, "id" | "name">): Lead {
  return blankProspect("Michael", {
    ...partial,
    property: partial.property || partial.company || partial.name,
    company: partial.company || partial.property || partial.name,
  });
}

export function createSeed(): Workspace {
  const created = new Date().toISOString();

  const companies: Company[] = [
    {
      id: "co-westside",
      name: "Westside Machinery",
      website: "https://westsidemachinery.example",
      phone: "+12145550110",
      email: "sales@westsidemachinery.example",
      city: "Dallas",
      state: "TX",
      sellerUrl: "https://example.com/sellers/westside",
      listingCount: 18,
      categories: ["Heavy Equipment", "Machinery"],
      avgItemValue: 18500,
      recurringCandidate: true,
      notes: "Looks like a working equipment dealer. Inventory turns. Treat as an account, not a one-off forklift chase.",
      createdAt: offset(-40, 9),
    },
    {
      id: "co-johns",
      name: "John’s Equipment",
      website: "",
      phone: "+13125550140",
      email: "",
      city: "Chicago",
      state: "IL",
      sellerUrl: "https://example.com/sellers/johns-equipment",
      listingCount: 4,
      categories: ["Heavy Equipment"],
      avgItemValue: 9200,
      recurringCandidate: true,
      notes: "Multiple commercial listings. Recurring shipper candidate.",
      createdAt: offset(-12, 11),
    },
    {
      id: "co-abc",
      name: "ABC Machinery",
      website: "https://abcmachinery.example",
      phone: "+16025550188",
      email: "mike@abcmachinery.example",
      city: "Phoenix",
      state: "AZ",
      sellerUrl: "",
      listingCount: 6,
      categories: ["Machinery", "CNC"],
      avgItemValue: 24000,
      recurringCandidate: true,
      notes: "Asked about a Dallas → Phoenix move. Interested in a recurring relationship.",
      createdAt: offset(-20, 10),
    },
  ];

  const leads: Lead[] = [
    lead({
      id: "lead-john",
      name: "John Reeves",
      company: "John’s Equipment",
      phone: "+13125550140",
      email: "",
      city: "Chicago",
      state: "IL",
      status: "Contacted",
      priority: "High",
      source: "Facebook Marketplace",
      attempts: 1,
      nextAction: "Follow up — he asked you to check back Monday",
      nextFollowUp: offset(0, 11),
      lastContactAt: offset(-2, 16),
      estimatedValue: 450,
      notes: "Asked if out-of-state buyers usually arrange their own transport. Check back Monday.",
      listingUrl: "https://example.com/listings/toyota-forklift-chicago",
      sellerUrl: "https://example.com/sellers/johns-equipment",
      category: "Heavy Equipment",
      equipmentType: "Forklift",
      freightScore: 94,
      scoreConfidence: "HIGH",
      scoreWhy: "Toyota forklift, commercial seller, value high enough to justify freight, and the listing already entertains delivery.",
      freightType: "Flatbed",
      recurringPotential: "Medium",
      askingPrice: 12500,
      origin: "Chicago, IL",
      destination: "Nashville, TN",
      listingTitle: "Toyota 8FGU25 forklift — 5,000 lb",
      listingDescription: "Dealer trade-in. Can load on a trailer. Buyer responsible for shipping.",
      companyId: "co-johns",
      tags: ["recurring-candidate"],
      createdAt: offset(-5, 9),
    }),
    lead({
      id: "lead-westside",
      name: "Westside Machinery",
      company: "Westside Machinery",
      phone: "+12145550110",
      email: "sales@westsidemachinery.example",
      city: "Dallas",
      state: "TX",
      status: "Ready to Contact",
      priority: "Critical",
      source: "Machinery Trader",
      attempts: 0,
      nextAction: "Send opener on the forklift lot — dealer inventory",
      nextFollowUp: "",
      estimatedValue: 2400,
      notes: "18 commercial equipment listings. This is an account hunt, not a one-load chase.",
      listingUrl: "https://example.com/listings/westside-lot",
      sellerUrl: "https://example.com/sellers/westside",
      website: "https://westsidemachinery.example",
      category: "Heavy Equipment",
      equipmentType: "Forklift",
      freightScore: 96,
      scoreConfidence: "HIGH",
      scoreWhy: "Equipment dealership with repeating inventory. Forklifts, generators, trailers, CNC. High recurring-shipper likelihood.",
      freightType: "Flatbed",
      recurringPotential: "High",
      askingPrice: 18900,
      origin: "Dallas, TX",
      listingTitle: "Dealer lot — mixed forklifts and generators",
      companyId: "co-westside",
      tags: ["recurring-candidate", "dealer"],
      createdAt: offset(-3, 14),
    }),
    lead({
      id: "lead-mike",
      name: "Mike Alvarez",
      company: "Mike Alvarez",
      phone: "",
      email: "",
      city: "Austin",
      state: "TX",
      status: "Discovered",
      priority: "Medium",
      source: "Facebook Marketplace",
      attempts: 0,
      nextAction: "Copy opener and open listing",
      listingUrl: "https://example.com/listings/harley-austin",
      category: "Motorcycles",
      equipmentType: "Motorcycle",
      freightScore: 71,
      scoreConfidence: "MEDIUM",
      scoreWhy: "Motorcycle transport is real, but this looks like a one-time private seller.",
      freightType: "Vehicle Transport",
      recurringPotential: "Low",
      askingPrice: 7800,
      origin: "Austin, TX",
      listingTitle: "2018 Harley-Davidson Street Bob",
      listingDescription: "Garage kept. Local pickup preferred, open to shipping.",
      createdAt: offset(-1, 19),
    }),
    lead({
      id: "lead-abc",
      name: "Mark Chen",
      company: "ABC Machinery",
      phone: "+16025550188",
      email: "mike@abcmachinery.example",
      city: "Phoenix",
      state: "AZ",
      status: "Quote Requested",
      priority: "High",
      source: "Referral",
      attempts: 3,
      nextAction: "Send Dallas → Phoenix rate",
      nextFollowUp: offset(0, 15),
      lastContactAt: offset(-1, 11),
      estimatedValue: 450,
      notes: "Gave phone number. Needs a forklift moved Dallas to Phoenix once the unit sells.",
      website: "https://abcmachinery.example",
      category: "Machinery",
      equipmentType: "CNC",
      freightScore: 91,
      scoreConfidence: "HIGH",
      scoreWhy: "Known lane, known commodity, seller already asked for a quote. Dealer-style inventory.",
      freightType: "Flatbed",
      recurringPotential: "High",
      askingPrice: 28500,
      origin: "Dallas, TX",
      destination: "Phoenix, AZ",
      listingTitle: "Haas VF-2 CNC mill",
      companyId: "co-abc",
      tags: ["recurring-candidate"],
      createdAt: offset(-18, 10),
    }),
    lead({
      id: "lead-helen",
      name: "Helen Park",
      company: "Park Restaurant Supply",
      phone: "+13055550122",
      email: "helen@parksupply.example",
      city: "Tampa",
      state: "FL",
      status: "Replied",
      priority: "High",
      source: "Craigslist",
      attempts: 2,
      nextAction: "Ask for pickup window on the walk-in cooler",
      nextFollowUp: offset(1, 9),
      lastContactAt: offset(-1, 17),
      category: "Commercial Equipment",
      equipmentType: "Walk-in cooler",
      freightScore: 82,
      scoreConfidence: "HIGH",
      scoreWhy: "Commercial kitchen equipment, oversized, likely LTL or specialized. Seller replied.",
      freightType: "LTL",
      recurringPotential: "Medium",
      askingPrice: 6400,
      origin: "Tampa, FL",
      listingTitle: "Walk-in cooler 8x10",
      listingUrl: "https://example.com/listings/tampa-cooler",
      createdAt: offset(-4, 12),
    }),
    lead({
      id: "lead-sam",
      name: "Sam Ortiz",
      company: "Ortiz Auctions",
      phone: "+18165550109",
      email: "lots@ortizauctions.example",
      city: "Kansas City",
      state: "MO",
      status: "Qualified",
      priority: "High",
      source: "Auction",
      attempts: 2,
      nextAction: "Confirm excavator dimensions after hammer falls",
      lastContactAt: offset(-3, 13),
      category: "Heavy Equipment",
      equipmentType: "Excavator",
      freightScore: 93,
      scoreConfidence: "HIGH",
      scoreWhy: "Mini excavator from an auction house. Specialized / oversized is likely. Auction houses ship constantly.",
      freightType: "Specialized / Oversized",
      recurringPotential: "High",
      askingPrice: 31200,
      origin: "Kansas City, MO",
      listingTitle: "2016 Cat 305.5E2 mini excavator",
      tags: ["recurring-candidate"],
      createdAt: offset(-9, 8),
    }),
    lead({
      id: "lead-riley",
      name: "Riley Chen",
      company: "Chen Property Group",
      phone: "+15593210104",
      email: "riley.chen@example.test",
      city: "Fresno",
      state: "CA",
      status: "Negotiating",
      priority: "High",
      owner: "Avery",
      source: "Partner",
      attempts: 4,
      nextAction: "Hold margin at $380 on the generator move",
      nextFollowUp: offset(-1, 15),
      lastContactAt: offset(-1, 15),
      estimatedValue: 380,
      notes: "Two generators. Wants a written rate before booking.",
      category: "Heavy Equipment",
      equipmentType: "Generator",
      freightScore: 84,
      scoreConfidence: "MEDIUM",
      scoreWhy: "Industrial generators, likely flatbed. Rate is in play.",
      freightType: "Flatbed",
      recurringPotential: "Medium",
      askingPrice: 22000,
      origin: "Fresno, CA",
      destination: "Reno, NV",
      listingTitle: "Kohler 150kW generators (pair)",
      createdAt: offset(-18, 11),
    }),
    lead({
      id: "lead-taylor",
      name: "Taylor Brooks",
      company: "Brooks Fabrication",
      phone: "+16195550103",
      email: "taylor.brooks@example.test",
      city: "San Diego",
      state: "CA",
      status: "Quote Sent",
      priority: "High",
      owner: "Avery",
      source: "Google",
      attempts: 1,
      nextAction: "Wait on quote — they have both decision-makers reviewing",
      nextFollowUp: offset(1, 8),
      lastContactAt: offset(-2, 10),
      estimatedValue: 290,
      category: "Machinery",
      equipmentType: "Press brake",
      freightScore: 79,
      scoreConfidence: "MEDIUM",
      scoreWhy: "Fabrication shop moving a press brake. One-time but qualified.",
      freightType: "Flatbed",
      recurringPotential: "Low",
      askingPrice: 16400,
      origin: "San Diego, CA",
      destination: "Tucson, AZ",
      listingTitle: "10-foot hydraulic press brake",
      createdAt: offset(-4, 16),
    }),
    lead({
      id: "lead-jordan",
      name: "Jordan Lee",
      company: "BrightPeak Rentals",
      phone: "+16615550101",
      email: "jordan.lee@example.test",
      city: "Bakersfield",
      state: "CA",
      status: "Load Won",
      priority: "High",
      attempts: 2,
      nextAction: "Carrier booked — confirm pickup window",
      lastContactAt: offset(-2, 11),
      estimatedValue: 420,
      category: "Heavy Equipment",
      equipmentType: "Scissor lift",
      freightScore: 88,
      scoreConfidence: "HIGH",
      scoreWhy: "Rental company moving a scissor lift. Load already won.",
      freightType: "Hotshot",
      recurringPotential: "High",
      askingPrice: 9800,
      origin: "Bakersfield, CA",
      destination: "Las Vegas, NV",
      listingTitle: "32ft scissor lift",
      tags: ["recurring-candidate"],
      createdAt: offset(-8, 10),
    }),
    lead({
      id: "lead-casey",
      name: "Casey Morgan",
      company: "Morgan Motors",
      phone: "+16615550102",
      email: "casey.morgan@example.test",
      city: "Bakersfield",
      state: "CA",
      status: "Recurring Account",
      priority: "Critical",
      source: "Referral",
      attempts: 5,
      nextAction: "Ask what is rolling off the lot next week",
      nextFollowUp: atHour(14),
      lastContactAt: offset(-2, 14),
      estimatedValue: 520,
      notes: "Used to arrange transport themselves. Now calling you first. Three delivered loads.",
      category: "Vehicles",
      equipmentType: "Pickup",
      freightScore: 90,
      scoreConfidence: "HIGH",
      scoreWhy: "Dealer already shipping with you. Recurring account.",
      freightType: "Vehicle Transport",
      recurringPotential: "High",
      origin: "Bakersfield, CA",
      destination: "Phoenix, AZ",
      tags: ["account"],
      createdAt: offset(-60, 9),
    }),
    lead({
      id: "lead-omar",
      name: "Omar Haddad",
      company: "Haddad Heavy Truck",
      phone: "+17025550121",
      email: "omar.haddad@example.test",
      city: "Las Vegas",
      state: "NV",
      status: "Contact Info Obtained",
      priority: "High",
      attempts: 2,
      nextAction: "Log the dump-body specs and quote",
      lastContactAt: offset(0, 9),
      category: "Trailers",
      equipmentType: "Dump trailer",
      freightScore: 77,
      scoreConfidence: "MEDIUM",
      scoreWhy: "Dump trailer. Gave a cell. Need destination.",
      freightType: "Flatbed",
      recurringPotential: "Medium",
      askingPrice: 11200,
      origin: "Las Vegas, NV",
      listingTitle: "16ft dump trailer",
      createdAt: offset(-6, 15),
    }),
    lead({
      id: "lead-sofa",
      name: "Priya Shah",
      company: "Priya Shah",
      phone: "",
      city: "Houston",
      state: "TX",
      status: "Load Lost",
      priority: "Low",
      source: "Facebook Marketplace",
      nextAction: "Skip — household item, not freight",
      category: "Household",
      equipmentType: "Sofa",
      freightScore: 8,
      scoreConfidence: "HIGH",
      scoreWhy: "Cheap household sofa. Parcel / local junk, not a freight opportunity.",
      freightType: "Unknown",
      recurringPotential: "Low",
      askingPrice: 120,
      listingTitle: "Ikea sectional, pickup only",
      listingDescription: "Must pick up this weekend. No delivery.",
      tags: ["not-interested"],
      createdAt: offset(-2, 20),
    }),
  ];

  const listings: Listing[] = [
    {
      id: "lst-john-forklift",
      leadId: "lead-john",
      companyId: "co-johns",
      source: "Facebook Marketplace",
      sourceUrl: "https://example.com/listings/toyota-forklift-chicago",
      title: "Toyota 8FGU25 forklift — 5,000 lb",
      description: "Dealer trade-in. Can load on a trailer. Buyer responsible for shipping.",
      sellerName: "John Reeves",
      sellerUrl: "https://example.com/sellers/johns-equipment",
      city: "Chicago",
      state: "IL",
      askingPrice: 12500,
      category: "Heavy Equipment",
      equipmentType: "Forklift",
      dimensions: "88 x 42 x 84 in",
      weight: "8,700 lb",
      quantity: 1,
      pickupLocation: "Chicago, IL",
      destination: "Nashville, TN",
      phone: "+13125550140",
      email: "",
      website: "",
      notes: "Asked to check back Monday.",
      imageUrls: [],
      discoveredAt: offset(-5, 9),
      priceHistory: [{ price: 12500, at: offset(-5, 9) }],
    },
    {
      id: "lst-west-1",
      leadId: "lead-westside",
      companyId: "co-westside",
      source: "Machinery Trader",
      sourceUrl: "https://example.com/listings/westside-lot",
      title: "Yale forklift lot — 4 units",
      description: "Dealer inventory. We sell nationwide.",
      sellerName: "Westside Machinery",
      sellerUrl: "https://example.com/sellers/westside",
      city: "Dallas",
      state: "TX",
      askingPrice: 18900,
      category: "Heavy Equipment",
      equipmentType: "Forklift",
      dimensions: "",
      weight: "9,000 lb",
      quantity: 4,
      pickupLocation: "Dallas, TX",
      destination: "",
      phone: "+12145550110",
      email: "sales@westsidemachinery.example",
      website: "https://westsidemachinery.example",
      notes: "",
      imageUrls: [],
      discoveredAt: offset(-3, 14),
      priceHistory: [{ price: 18900, at: offset(-3, 14) }],
    },
    {
      id: "lst-abc-cnc",
      leadId: "lead-abc",
      companyId: "co-abc",
      source: "Referral",
      sourceUrl: "",
      title: "Haas VF-2 CNC mill",
      description: "Needs a quote Dallas to Phoenix once it sells.",
      sellerName: "Mark Chen",
      sellerUrl: "",
      city: "Phoenix",
      state: "AZ",
      askingPrice: 28500,
      category: "Machinery",
      equipmentType: "CNC",
      dimensions: "120 x 64 x 96 in",
      weight: "7,200 lb",
      quantity: 1,
      pickupLocation: "Dallas, TX",
      destination: "Phoenix, AZ",
      phone: "+16025550188",
      email: "mike@abcmachinery.example",
      website: "https://abcmachinery.example",
      notes: "",
      imageUrls: [],
      discoveredAt: offset(-18, 10),
      priceHistory: [{ price: 28500, at: offset(-18, 10) }],
    },
  ];

  const analyses: FreightAnalysis[] = leads.map((item) => ({
    leadId: item.id,
    score: item.freightScore || 0,
    confidence: item.scoreConfidence || "LOW",
    why: item.scoreWhy || "",
    freightType: item.freightType || "Unknown",
    recurringPotential: item.recurringPotential || "Low",
    known: ["Listing title", item.origin || item.city, item.askingPrice != null ? `Asking price $${item.askingPrice}` : ""].filter(Boolean),
    estimates: item.freightType && item.freightType !== "Unknown" ? [`Likely equipment: ${item.freightType}`] : [],
    unknown: item.destination ? [] : ["Destination"],
    openerCasual: `Hey, random question about the ${(item.equipmentType || "item").toLowerCase()}. If somebody bought it from another state, do you already have someone you normally use to transport it?`,
    openerDirect: `If this ${(item.equipmentType || "item").toLowerCase()} needs to move out of state, I can quote it. Do you already have a transporter lined up?`,
    openerBusiness: `When this ${(item.equipmentType || "item").toLowerCase()} sells, do you typically arrange freight or should I send a rate?`,
    openerShort: `Does the ${(item.equipmentType || "item").toLowerCase()} need shipping, or is it pickup only?`,
    openerFollowUp: `Circling back on the ${(item.equipmentType || "item").toLowerCase()} — any movement on transport yet?`,
    analyzedAt: created,
  }));

  const opportunities: Opportunity[] = leads.map((item) => ({
    id: `opp-${item.id.replace("lead-", "")}`,
    leadId: item.id,
    name: item.name,
    property: item.company || item.property,
    stage: item.status,
    value: item.estimatedValue || Math.round((item.askingPrice || 0) * 0.08),
    probability: item.status === "Load Won" || item.status === "Recurring Account" ? 100 : item.status === "Negotiating" ? 55 : item.status === "Quote Sent" ? 40 : 15,
    owner: item.owner,
    source: item.source,
    nextAction: item.nextAction,
    expectedClose: "",
    notes: item.notes,
    createdAt: item.createdAt,
    updatedAt: created,
    stageEnteredAt: item.updatedAt,
    history: [],
    origin: item.origin,
    destination: item.destination,
    freightType: item.freightType,
    commodity: item.listingTitle,
  }));

  const callbacks: Callback[] = [
    {
      id: "cb-john",
      leadId: "lead-john",
      type: "hot",
      dueAt: offset(0, 11),
      reason: "Asked me to check back Monday.",
      assignedUser: "Michael",
      notes: "Forklift seller. Casual opener already sent.",
      status: "open",
      createdAt: offset(-2, 16),
    },
    {
      id: "cb-westside",
      leadId: "lead-westside",
      type: "promising",
      dueAt: offset(0, 13),
      reason: "No reply after first message.",
      assignedUser: "Michael",
      notes: "Dealer lot — keep it short.",
      status: "open",
      createdAt: offset(-1, 14),
    },
    {
      id: "cb-abc",
      leadId: "lead-abc",
      type: "hot",
      dueAt: offset(0, 15),
      reason: "Needs shipping quote once equipment sells.",
      assignedUser: "Michael",
      notes: "Dallas → Phoenix CNC.",
      status: "open",
      createdAt: offset(-1, 11),
    },
    {
      id: "cb-casey",
      leadId: "lead-casey",
      type: "promising",
      dueAt: atHour(14),
      reason: "Interested in recurring transport relationship.",
      assignedUser: "Michael",
      notes: "Ask what’s coming off the lot.",
      status: "open",
      createdAt: offset(-1, 14),
    },
    {
      id: "cb-riley",
      leadId: "lead-riley",
      type: "hot",
      dueAt: offset(-1, 15),
      reason: "Quote still open — hold margin.",
      assignedUser: "Avery",
      notes: "Overdue. Generators Fresno → Reno.",
      status: "open",
      createdAt: offset(-3, 15),
    },
    {
      id: "cb-helen",
      leadId: "lead-helen",
      type: "standard",
      dueAt: offset(1, 9),
      reason: "Replied — confirm walk-in cooler pickup window.",
      assignedUser: "Michael",
      notes: "",
      status: "open",
      createdAt: offset(-1, 17),
    },
  ];

  const quotes: Quote[] = [
    {
      id: "qt-abc",
      leadId: "lead-abc",
      opportunityId: "opp-abc",
      origin: "Dallas, TX",
      destination: "Phoenix, AZ",
      commodity: "Haas VF-2 CNC mill",
      equipmentType: "Flatbed",
      customerRate: 2100,
      carrierCost: 1650,
      status: "requested",
      notes: "Waiting on sale to book.",
      createdAt: offset(-1, 11),
    },
    {
      id: "qt-taylor",
      leadId: "lead-taylor",
      opportunityId: "opp-taylor",
      origin: "San Diego, CA",
      destination: "Tucson, AZ",
      commodity: "Press brake",
      equipmentType: "Flatbed",
      customerRate: 1450,
      carrierCost: 1160,
      status: "sent",
      notes: "",
      createdAt: offset(-2, 10),
    },
  ];

  const shipments: Shipment[] = [
    {
      id: "shp-jordan",
      leadId: "lead-jordan",
      customer: "BrightPeak Rentals",
      contact: "Jordan Lee",
      origin: "Bakersfield, CA",
      destination: "Las Vegas, NV",
      pickupDate: offset(1, 8).slice(0, 10),
      deliveryDate: offset(2, 16).slice(0, 10),
      commodity: "32ft scissor lift",
      weight: "3,400 lb",
      dimensions: "32 ft",
      equipmentType: "Hotshot",
      carrier: "Desert Hotshot",
      carrierRate: 980,
      customerRate: 1400,
      status: "Carrier Booked",
      reference: "LUM-1042",
      notes: "Load won. Confirm pickup window.",
      createdAt: offset(-2, 11),
      updatedAt: created,
    },
    {
      id: "shp-casey-1",
      leadId: "lead-casey",
      accountId: "lead-casey",
      customer: "Morgan Motors",
      contact: "Casey Morgan",
      origin: "Bakersfield, CA",
      destination: "Phoenix, AZ",
      pickupDate: offset(-12, 9).slice(0, 10),
      deliveryDate: offset(-11, 17).slice(0, 10),
      commodity: "Used F-150",
      weight: "4,800 lb",
      dimensions: "",
      equipmentType: "Vehicle Transport",
      carrier: "West Haul",
      carrierRate: 780,
      customerRate: 1250,
      status: "Paid",
      reference: "LUM-0988",
      notes: "Delivered and paid.",
      createdAt: offset(-14, 10),
      updatedAt: offset(-10, 12),
    },
    {
      id: "shp-abc",
      leadId: "lead-abc",
      quoteId: "qt-abc",
      customer: "ABC Machinery",
      contact: "Mark Chen",
      origin: "Dallas, TX",
      destination: "Phoenix, AZ",
      pickupDate: "",
      deliveryDate: "",
      commodity: "Haas VF-2 CNC mill",
      weight: "7,200 lb",
      dimensions: "120 x 64 x 96 in",
      equipmentType: "Flatbed",
      carrier: "",
      carrierRate: 1650,
      customerRate: 2100,
      status: "Quote",
      reference: "LUM-1107",
      notes: "Quote requested. Not booked yet.",
      createdAt: offset(-1, 11),
      updatedAt: created,
    },
  ];

  const savedSearches: SavedSearch[] = [
    { id: "ss-tx-heavy", name: "Heavy Equipment – Texas", keywords: "forklift excavator bobcat", source: "Machinery Trader", location: "TX", category: "Heavy Equipment", minValue: 3000, minFreightScore: 70, status: "Discovered", huntUrl: "https://www.machinerytrader.com/listings/search?keywords=forklift", createdAt: created },
    { id: "ss-fork-mw", name: "Forklifts – Midwest", keywords: "forklift", source: "Facebook Marketplace", location: "IL,MO,OH", category: "Heavy Equipment", minValue: 4000, minFreightScore: 75, status: "", huntUrl: "https://www.facebook.com/marketplace/search/?query=forklift", createdAt: created },
    { id: "ss-cnc", name: "CNC Machinery – Nationwide", keywords: "CNC mill lathe", source: "Machinery Trader", location: "", category: "Machinery", minValue: 8000, minFreightScore: 80, status: "", huntUrl: "https://www.machinerytrader.com/listings/search?keywords=CNC", createdAt: created },
    { id: "ss-maps-tx", name: "Maps dealers – Texas", keywords: "forklift dealer", source: "Google", location: "TX", category: "Heavy Equipment", minValue: null, minFreightScore: 70, status: "", huntUrl: "https://www.google.com/maps/search/forklift+dealer+Texas", createdAt: created },
  ];

  const appointments: Appointment[] = [];

  return {
    version: 3,
    brand: "azimuth",
    leads,
    opportunities,
    callbacks,
    appointments,
    activities: [
      { id: "act-seed", entityType: "workspace", entityId: "azimuth", type: "seeded", detail: "Freight workspace loaded. Example prospects only.", at: created },
      { id: "act-john-msg", entityType: "lead", entityId: "lead-john", type: "message", detail: "Sent casual opener on the Toyota forklift.", at: offset(-2, 16) },
      { id: "act-abc-phone", entityType: "lead", entityId: "lead-abc", type: "status_change", detail: "Mark gave a phone number. Moved to Quote Requested.", at: offset(-1, 11) },
    ],
    kpiEvents: [
      { id: "kpi-1", type: "prospect_captured", leadId: "lead-john", at: offset(-5, 9) },
      { id: "kpi-2", type: "message_sent", leadId: "lead-john", at: offset(-2, 16) },
      { id: "kpi-3", type: "reply", leadId: "lead-helen", at: offset(-1, 17) },
      { id: "kpi-4", type: "quote_requested", leadId: "lead-abc", at: offset(-1, 11) },
      { id: "kpi-5", type: "load_won", leadId: "lead-jordan", at: offset(-2, 11) },
      { id: "kpi-6", type: "message_sent", leadId: "lead-westside", at: offset(-1, 14) },
      { id: "kpi-7", type: "call", leadId: "lead-casey", at: offset(-2, 14) },
    ],
    designs: {},
    proposals: {},
    callLogs: [
      {
        id: "call-casey",
        leadId: "lead-casey",
        outcome: "connected",
        duration: 240,
        notes: "Wants you on the next three trucks off the lot.",
        at: offset(-2, 14),
      },
    ],
    listings,
    companies,
    quotes,
    shipments,
    carriers: [],
    savedSearches,
    analyses,
    settings: {
      operator: "Michael",
      dialTarget: 40,
      defaultOwner: "Michael",
      density: "comfortable",
    },
    updatedAt: created,
    revision: 1,
  };
}

function normalizeLead(item: Lead): Lead {
  const status = mapLegacyStage(item.status);
  return blankProspect(item.owner || "Michael", {
    ...item,
    status,
    company: item.company || item.property,
    property: item.property || item.company || item.name,
    tags: item.tags || [],
    freightScore: item.freightScore ?? 0,
    freightType: item.freightType || "Unknown",
    recurringPotential: item.recurringPotential || "Low",
    scoreConfidence: item.scoreConfidence || "LOW",
  });
}

export function normalizeWorkspace(workspace: Workspace): Workspace {
  const version = Number(workspace.version) || 0;
  const freightFields = {
    listings: workspace.listings || [],
    companies: workspace.companies || [],
    quotes: workspace.quotes || [],
    shipments: workspace.shipments || [],
    carriers: workspace.carriers || [],
    savedSearches: workspace.savedSearches || [],
    analyses: workspace.analyses || [],
  };

  return {
    ...workspace,
    ...freightFields,
    version: Math.max(version, 3),
    brand: "azimuth",
    revision: Number(workspace.revision) || 0,
    leads: (workspace.leads || []).map(normalizeLead),
    opportunities: (workspace.opportunities || []).map((item) => ({
      ...item,
      stage: mapLegacyStage(item.stage),
      history: item.history || [],
    })),
    callbacks: workspace.callbacks || [],
    appointments: workspace.appointments || [],
    activities: workspace.activities || [],
    kpiEvents: workspace.kpiEvents || [],
    designs: version >= 3 ? workspace.designs || {} : {},
    proposals: workspace.proposals || {},
    callLogs: workspace.callLogs || [],
  };
}

export function isWorkspace(value: unknown): value is Workspace {
  if (!value || typeof value !== "object" || Array.isArray(value)) return false;
  const record = value as Record<string, unknown>;
  return record.brand === "azimuth" && Array.isArray(record.leads) && Array.isArray(record.opportunities);
}
